import { COLUMN_EMPTY_PREFIX } from "@1771technologies/grid-constants";

/**
 * Checks if a column is an empty placeholder column by examining its id.
 *
 * Empty columns are special placeholder columns that represent collapsed group space
 * in the grid. They maintain visual structure when groups are collapsed.
 *
 * @typeParam T - Type of the column object, must include at least an `id` property
 * @param column - The column object to check
 * @returns `true` if the column is an empty placeholder, `false` otherwise
 *
 * @example
 * ```typescript
 * const regularColumn = { id: 'user-name', width: 100 };
 * isEmptyColumn(regularColumn); // false
 *
 * const emptyColumn = { id: 'lytenyte-empty:group1|>empty', width: 100 };
 * isEmptyColumn(emptyColumn); // true
 * ```
 *
 * @see columnIsEmptyById - For checking just a column ID string
 */
export function columnIsEmpty<T extends { id: string }>(column: T) {
  return columnIsEmptyById(column.id);
}

/**
 * Checks if a column ID represents an empty placeholder column.
 *
 * This is a lower-level function that directly checks if the ID starts with
 * the empty column prefix. It's used internally by {@link columnIsEmpty} and
 * can be used directly when only the column ID is available.
 *
 * @param id - The column ID to check
 * @returns `true` if the ID indicates an empty placeholder column, `false` otherwise
 *
 * @example
 * ```typescript
 * isEmptyColumnById('user-name'); // false
 * isEmptyColumnById('lytenyte-empty:group1|>empty'); // true
 * ```
 *
 * @remarks
 * Empty column IDs are generated by the {@link columnEmptyKey} function and
 * always start with a specific prefix defined in grid constants.
 */
export function columnIsEmptyById(id: string) {
  return id.startsWith(COLUMN_EMPTY_PREFIX);
}
