import type { Theme } from "./types";

// prettier-ignore
export const t: Theme = {
  colors: {
    gradient_shadow:                    "var(--lng1771-gradient-shadow)",
    
    primary_05:                         "var(--lng1771-primary-05)",
    primary_10:                         "var(--lng1771-primary-10)",
    primary_30:                         "var(--lng1771-primary-30)",
    primary_50:                         "var(--lng1771-primary-50)",
    primary_70:                         "var(--lng1771-primary-70)",
    primary_90:                         "var(--lng1771-primary-90)",
    
    gray_00:                            "var(--lng1771-gray-00)",
    gray_02:                            "var(--lng1771-gray-02)",
    gray_05:                            "var(--lng1771-gray-05)",
    gray_10:                            "var(--lng1771-gray-10)",
    gray_20:                            "var(--lng1771-gray-20)",
    gray_30:                            "var(--lng1771-gray-30)",
    gray_40:                            "var(--lng1771-gray-40)",
    gray_50:                            "var(--lng1771-gray-50)",
    gray_60:                            "var(--lng1771-gray-60)",
    gray_70:                            "var(--lng1771-gray-70)",
    gray_80:                            "var(--lng1771-gray-80)",
    gray_90:                            "var(--lng1771-gray-90)",
    gray_100:                           "var(--lng1771-gray-100)",
    
    backgrounds_default:                 "var(--lng1771-backgrounds-default)",
    backgrounds_strong:                  "var(--lng1771-backgrounds-strong)",
    backgrounds_light:                   "var(--lng1771-backgrounds-light)",
    backgrounds_button_light:            "var(--lng1771-backgrounds-button-light)",
    backgrounds_context_menu:            "var(--lng1771-backgrounds-context-menu)",
    backgrounds_floating_panel:          "var(--lng1771-backgrounds-floating-panel)",
    backgrounds_form_field:              "var(--lng1771-backgrounds-form-field)",
    backgrounds_page:                    "var(--lng1771-backgrounds-page)",
    backgrounds_row_alternate:           "var(--lng1771-backgrounds-row-alternate)",
    backgrounds_row_hover:               "var(--lng1771-backgrounds-row-hover)",
    backgrounds_ui_panel:                "var(--lng1771-backgrounds-ui-panel)",
    backgrounds_row_selected:            "var(--lng1771-backgrounds-row-selected)",
    
    borders_row:                         "var(--lng1771-borders-row)",
    borders_default:                     "var(--lng1771-borders-default)",
    borders_strong:                      "var(--lng1771-borders-strong)",
    borders_button_light:                "var(--lng1771-borders-button-light)",
    borders_context_menu:                "var(--lng1771-borders-context-menu)",
    borders_field_and_button:            "var(--lng1771-borders-field-and-button)",
    borders_field_and_button_shadow:     "var(--lng1771-borders-field-and-button-shadow)",
    borders_icons_default:               "var(--lng1771-borders-icons-default)",
    borders_ui_panel:                    "var(--lng1771-borders-ui-panel)",
    borders_floating_panel:              "var(--lng1771-borders-ui-panel)",
    borders_separator:                   "var(--lng1771-borders-separator)",
    
    system_plain_pill_fill:              "var(--lng1771-system-plain-pill-fill)",
    system_column_pill_fill:             "var(--lng1771-system-column-pill-fill)",
    system_column_pill_stroke:           "var(--lng1771-system-column-pill-stroke)",
    system_pivot_pill_fill:              "var(--lng1771-system-pivot-pill-fill)",
    system_pivot_pill_stroke:            "var(--lng1771-system-pivot-pill-stroke)",
    system_group_pill_fill:              "var(--lng1771-system-group-pill-fill)",
    system_group_pill_stroke:            "var(--lng1771-system-group-pill-stroke)",
    system_pill_icon_color:              "var(--lng1771-system-pill-icon-color)",
    
    system_green_10:                     "var(--lng1771-system-green-10)",
    system_green_30:                     "var(--lng1771-system-green-30)",
    system_green_50:                     "var(--lng1771-system-green-50)",
    system_green_70:                     "var(--lng1771-system-green-70)",
    system_green_90:                     "var(--lng1771-system-green-90)",
    
    system_info_10:                      "var(--lng1771-system-info-10)",
    system_info_30:                      "var(--lng1771-system-info-30)",
    system_info_50:                      "var(--lng1771-system-info-50)",
    system_info_70:                      "var(--lng1771-system-info-70)",
    system_info_90:                      "var(--lng1771-system-info-90)",
    
    system_red_10:                       "var(--lng1771-system-red-10)",
    system_red_30:                       "var(--lng1771-system-red-30)",
    system_red_50:                       "var(--lng1771-system-red-50)",
    system_red_70:                       "var(--lng1771-system-red-70)",
    system_red_90:                       "var(--lng1771-system-red-90)",
    
    system_yellow_10:                    "var(--lng1771-system-yellow-10)",
    system_yellow_30:                    "var(--lng1771-system-yellow-30)",
    system_yellow_50:                    "var(--lng1771-system-yellow-50)",
    system_yellow_70:                    "var(--lng1771-system-yellow-70)",
    system_yellow_90:                    "var(--lng1771-system-yellow-90)",
    
    text_hyperlink:                      "var(--lng1771-text-hyperlink)",
    text_primary_button:                 "var(--lng1771-text-primary-button)",
    text_dark:                           "var(--lng1771-text-dark)",
    text_light:                          "var(--lng1771-text-light)",
    text_medium:                         "var(--lng1771-text-medium)",
    text_x_light:                        "var(--lng1771-text-x-light)",
  },
  transitions: {
    fn:                                  "var(--lng1771-transition-fn)",
    slow:                                "var(--lng1771-transition-slow)",
    normal:                              "var(--lng1771-transition-normal)",
    fast:                                "var(--lng1771-transition-fast)",
    vfast:                               "var(--lng1771-transition-vfast)",
  },
  shadows: {
    100:                                 "var(--lng1771-shadow-100)",
    200:                                 "var(--lng1771-shadow-200)",
    300:                                 "var(--lng1771-shadow-300)",
    400:                                 "var(--lng1771-shadow-400)",
    500:                                 "var(--lng1771-shadow-500)",
    600:                                 "var(--lng1771-shadow-600)",
    700:                                 "var(--lng1771-shadow-700)",
    
    dark_100:                            "var(--lng1771-shadow-100-dark)",
    dark_200:                            "var(--lng1771-shadow-200-dark)",
    dark_300:                            "var(--lng1771-shadow-300-dark)",
    dark_400:                            "var(--lng1771-shadow-400-dark)",
    dark_500:                            "var(--lng1771-shadow-500-dark)",
    dark_600:                            "var(--lng1771-shadow-600-dark)",
    dark_700:                            "var(--lng1771-shadow-700-dark)",

    field_and_button:                    'var(--lng1771-shadow-field-and-button)',
  },
  spacing: {
    space_02:                            "var(--lng1771-space-02)",
    space_05:                            "var(--lng1771-space-05)",
    space_10:                            "var(--lng1771-space-10)",
    space_20:                            "var(--lng1771-space-20)",
    space_25:                            "var(--lng1771-space-25)",
    space_30:                            "var(--lng1771-space-30)",
    space_40:                            "var(--lng1771-space-40)",
    space_50:                            "var(--lng1771-space-50)",
    space_60:                            "var(--lng1771-space-60)",
    space_65:                            "var(--lng1771-space-65)",
    space_70:                            "var(--lng1771-space-70)",
    space_80:                            "var(--lng1771-space-80)",
    space_90:                            "var(--lng1771-space-90)",
    space_100:                           "var(--lng1771-space-100)",

    input_height:                        'var(--lng1771-input-height)',

    box_radius_regular:                  "var(--lng1771-box-radius-regular)",
    box_radius_medium:                   "var(--lng1771-box-radius-medium)",
    box_radius_large:                    "var(--lng1771-box-radius-large)",
    
    field_radius_large:                  "var(--lng1771-field-radius-large)",
    field_radius_medium:                 "var(--lng1771-field-radius-medium)",
    field_radius_small:                  "var(--lng1771-field-radius-small)",
    
    field_padding_small:                 "var(--lng1771-field-padding-small)",
    field_padding_medium:                "var(--lng1771-field-padding-medium)",
    field_padding_large:                 "var(--lng1771-field-padding-large)",
    field_padding_xlarge:                "var(--lng1771-field-padding-xlarge)",
    
    thead_vertical_padding:              "var(--lng1771-thead-vertical-padding)",
    cell_vertical_padding:               "var(--lng1771-cell-vertical-padding)",
    cell_horizontal_padding:             "var(--lng1771-cell-horizontal-padding)",
  },
  typography: {
      typeface_headline:                   "var(--lng1771-typeface-headline)",
      typeface_body:                       "var(--lng1771-typeface-body)",
      
      h1:                                  "var(--lng1771-h1)",
      h2:                                  "var(--lng1771-h2)",
      h3:                                  "var(--lng1771-h3)",
      h4:                                  "var(--lng1771-h4)",
      h5:                                  "var(--lng1771-h5)",
      h6:                                  "var(--lng1771-h6)",
      
      body_l:                              "var(--lng1771-body-l)",
      body_m:                              "var(--lng1771-body-m)",
      body_s:                              "var(--lng1771-body-s)",
      body_xs:                             "var(--lng1771-body-xs)",
  },
} as const;
