import type { Metadata } from "next";
import { Archivo, Inter, Roboto_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./main.css";
import "./doc.css";
import { Header } from "./components/header";
import { SecondaryHeader } from "./components/secondary-header/secondary-header";

const archivo = Archivo({
  variable: "--font-archivo-v",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter-v",
  subsets: ["latin"],
});
const mono = Roboto_Mono({
  variable: "--font-mono-v",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${archivo.variable} ${inter.variable} ${mono.variable}`}
      >
        <ThemeProvider>
          <div className="h-header w-full-client fixed top-0 z-50 flex flex-col border-b border-gray-200 bg-gray-50 px-6">
            <Header />
            <SecondaryHeader />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
