import type { ColumnEnterpriseReact } from "@1771technologies/grid-types";

export const stockColumns: ColumnEnterpriseReact<(string | null | number)[]>[] = [
  {
    id: "symbol",
    headerName: "Symbol",
    field: 0,
    width: 280,
    aggFunc: "count",
  },
  {
    id: "exchange",
    headerName: "Exchange",
    field: 15,
    width: 110,
    rowGroupable: true,
    columnPivotable: true,
    aggFunc: "count",
  },
  {
    id: "price",
    headerName: "Price",
    field: 3,
    width: 110,
    type: "number",
    aggFunc: "avg",
  },
  {
    id: "price-change",
    headerName: "Change %",
    field: 5,
    width: 120,
    type: "number",
    aggFunc: "avg",
  },

  {
    id: "analyst rating",
    headerName: "Analyst Rating",
    field: 2,
  },
  {
    id: "eps-diluted",
    headerName: "EPS dil",
    headerSecondaryLabel: "TTM",
    field: 11,
    type: "number",
    aggFunc: "avg",
  },
  {
    id: "volume",
    headerName: "Volume",
    field: 6,
    type: "number",
    aggFunc: "sum",
  },
  {
    id: "market-capitalization",
    headerName: "Market Cap",
    field: 8,
    type: "number",
    aggFunc: "avg",
  },
  {
    id: "price-earning",
    headerName: "P/E",
    field: 10,
    width: 80,
    type: "number",
    aggFunc: "avg",
  },
  {
    id: "eps-diluted-growth",
    headerName: "EPS dil growth",
    headerSecondaryLabel: "TTM YoY",
    field: 13,
    type: "number",
    aggFunc: "avg",
  },
  {
    id: "dividend yield",
    headerName: "Div yield %",
    headerSecondaryLabel: "TTM",
    field: 14,
    type: "number",
    aggFunc: "avg",
  },

  {
    id: "rel-volume",
    headerName: "Rel Volume",
    field: 7,
    width: 120,
    type: "number",
    aggFunc: "avg",
  },
  {
    id: "industry",
    headerName: "Industry",
    field: 17,
    width: 250,
    rowGroupable: true,
    columnPivotable: true,
    aggFunc: "count",
  },
  {
    id: "sector",
    headerName: "Sector",
    field: 16,
    width: 180,
    rowGroupable: true,
    columnPivotable: true,
    aggFunc: "count",
  },
];
