export const data = {
  name: "root",
  kind: "folder",
  size: 0,
  modified: "2026-01-22T09:00:00Z",
  children: [
    {
      name: "package.json",
      kind: "file",
      size: 1840,
      modified: "2026-01-21T18:12:00Z",
      lastEditedBy: "Ava Chen",
      permissions: "rw-r--r--",
    },
    {
      name: "package-lock.json",
      kind: "file",
      size: 92000,
      modified: "2026-01-21T18:12:30Z",
      lastEditedBy: "Ava Chen",
      permissions: "rw-r--r--",
    },
    {
      name: "README.md",
      kind: "file",
      size: 1240,
      modified: "2026-01-20T10:05:00Z",
      lastEditedBy: "Samir Patel",
      permissions: "rw-r--r--",
    },
    {
      name: ".gitignore",
      kind: "file",
      size: 180,
      modified: "2026-01-19T09:00:00Z",
      lastEditedBy: "Samir Patel",
      permissions: "rw-r--r--",
    },
    {
      name: ".env",
      kind: "file",
      size: 220,
      modified: "2026-01-21T08:30:00Z",
      lastEditedBy: "Mina Alvarez",
      permissions: "rw-------",
    },

    {
      name: "public",
      kind: "folder",
      size: 0,
      modified: "2026-01-18T12:00:00Z",
      children: [
        {
          name: "index.html",
          kind: "file",
          size: 3420,
          modified: "2026-01-18T12:01:00Z",
          lastEditedBy: "Noah Brooks",
          permissions: "rw-r--r--",
        },
        {
          name: "favicon.ico",
          kind: "file",
          size: 5430,
          modified: "2026-01-18T12:01:30Z",
          lastEditedBy: "Noah Brooks",
          permissions: "rw-r--r--",
        },
        {
          name: "manifest.json",
          kind: "file",
          size: 820,
          modified: "2026-01-18T12:02:00Z",
          lastEditedBy: "Noah Brooks",
          permissions: "rw-r--r--",
        },
        {
          name: "assets",
          kind: "folder",
          size: 0,
          modified: "2026-01-17T15:40:00Z",
          children: [
            {
              name: "logo.svg",
              kind: "file",
              size: 2048,
              modified: "2026-01-17T15:42:00Z",
              lastEditedBy: "Priya Nair",
              permissions: "rw-r--r--",
            },
            {
              name: "hero.png",
              kind: "file",
              size: 482000,
              modified: "2026-01-17T15:45:00Z",
              lastEditedBy: "Priya Nair",
              permissions: "rw-r--r--",
            },
          ],
        },
      ],
    },

    {
      name: "src",
      kind: "folder",
      size: 0,
      modified: "2026-01-22T08:30:00Z",
      children: [
        {
          name: "assets",
          kind: "folder",
          size: 0,
          modified: "2026-01-20T14:00:00Z",
          children: [
            {
              name: "global.css",
              kind: "file",
              size: 2140,
              modified: "2026-01-20T14:05:00Z",
              lastEditedBy: "Jordan Kim",
              permissions: "rw-r--r--",
            },
            {
              name: "variables.css",
              kind: "file",
              size: 980,
              modified: "2026-01-20T14:04:00Z",
              lastEditedBy: "Jordan Kim",
              permissions: "rw-r--r--",
            },
          ],
        },

        {
          name: "components",
          kind: "folder",
          size: 0,
          modified: "2026-01-21T09:30:00Z",
          children: [
            {
              name: "Button",
              kind: "folder",
              size: 0,
              modified: "2026-01-21T09:31:00Z",
              children: [
                {
                  name: "Button.jsx",
                  kind: "file",
                  size: 1620,
                  modified: "2026-01-21T09:35:00Z",
                  lastEditedBy: "Lee Beydoun",
                  permissions: "rw-r--r--",
                },
                {
                  name: "Button.module.css",
                  kind: "file",
                  size: 740,
                  modified: "2026-01-21T09:34:00Z",
                  lastEditedBy: "Lee Beydoun",
                  permissions: "rw-r--r--",
                },
                {
                  name: "Button.test.jsx",
                  kind: "file",
                  size: 1280,
                  modified: "2026-01-21T09:36:00Z",
                  lastEditedBy: "Ava Chen",
                  permissions: "rw-r--r--",
                },
              ],
            },

            {
              name: "Modal",
              kind: "folder",
              size: 0,
              modified: "2026-01-21T11:10:00Z",
              children: [
                {
                  name: "Modal.jsx",
                  kind: "file",
                  size: 1980,
                  modified: "2026-01-21T11:15:00Z",
                  lastEditedBy: "Mina Alvarez",
                  permissions: "rw-r--r--",
                },
                {
                  name: "Modal.css",
                  kind: "file",
                  size: 860,
                  modified: "2026-01-21T11:14:00Z",
                  lastEditedBy: "Mina Alvarez",
                  permissions: "rw-r--r--",
                },
              ],
            },
          ],
        },

        {
          name: "hooks",
          kind: "folder",
          size: 0,
          modified: "2026-01-19T16:00:00Z",
          children: [
            {
              name: "useAuth.js",
              kind: "file",
              size: 1320,
              modified: "2026-01-19T16:05:00Z",
              lastEditedBy: "Samir Patel",
              permissions: "rw-r--r--",
            },
            {
              name: "useFetch.js",
              kind: "file",
              size: 1740,
              modified: "2026-01-19T16:06:00Z",
              lastEditedBy: "Samir Patel",
              permissions: "rw-r--r--",
            },
          ],
        },

        {
          name: "context",
          kind: "folder",
          size: 0,
          modified: "2026-01-20T10:40:00Z",
          children: [
            {
              name: "AuthContext.jsx",
              kind: "file",
              size: 1560,
              modified: "2026-01-20T10:42:00Z",
              lastEditedBy: "Jordan Kim",
              permissions: "rw-r--r--",
            },
          ],
        },

        {
          name: "services",
          kind: "folder",
          size: 0,
          modified: "2026-01-20T11:30:00Z",
          children: [
            {
              name: "api.js",
              kind: "file",
              size: 980,
              modified: "2026-01-20T11:32:00Z",
              lastEditedBy: "Noah Brooks",
              permissions: "rw-r--r--",
            },
            {
              name: "authService.js",
              kind: "file",
              size: 1420,
              modified: "2026-01-20T11:33:00Z",
              lastEditedBy: "Noah Brooks",
              permissions: "rw-r--r--",
            },
          ],
        },

        {
          name: "utils",
          kind: "folder",
          size: 0,
          modified: "2026-01-19T15:10:00Z",
          children: [
            {
              name: "constants.js",
              kind: "file",
              size: 540,
              modified: "2026-01-19T15:12:00Z",
              lastEditedBy: "Priya Nair",
              permissions: "rw-r--r--",
            },
            {
              name: "formatDate.js",
              kind: "file",
              size: 620,
              modified: "2026-01-19T15:11:00Z",
              lastEditedBy: "Priya Nair",
              permissions: "rw-r--r--",
            },
          ],
        },

        {
          name: "routes.jsx",
          kind: "file",
          size: 1240,
          modified: "2026-01-22T08:10:00Z",
          lastEditedBy: "Lee Beydoun",
          permissions: "rw-r--r--",
        },
        {
          name: "App.jsx",
          kind: "file",
          size: 2140,
          modified: "2026-01-22T08:20:00Z",
          lastEditedBy: "Lee Beydoun",
          permissions: "rw-r--r--",
        },
        {
          name: "main.jsx",
          kind: "file",
          size: 860,
          modified: "2026-01-22T08:25:00Z",
          lastEditedBy: "Lee Beydoun",
          permissions: "rw-r--r--",
        },
      ],
    },

    {
      name: "tests",
      kind: "folder",
      size: 0,
      modified: "2026-01-21T13:00:00Z",
      children: [
        {
          name: "setupTests.js",
          kind: "file",
          size: 520,
          modified: "2026-01-21T13:01:00Z",
          lastEditedBy: "Ava Chen",
          permissions: "rw-r--r--",
        },
        {
          name: "App.test.jsx",
          kind: "file",
          size: 1620,
          modified: "2026-01-21T13:02:00Z",
          lastEditedBy: "Ava Chen",
          permissions: "rw-r--r--",
        },
      ],
    },

    {
      name: "config",
      kind: "folder",
      size: 0,
      modified: "2026-01-18T17:00:00Z",
      children: [
        {
          name: "vite.config.js",
          kind: "file",
          size: 1120,
          modified: "2026-01-18T17:02:00Z",
          lastEditedBy: "Samir Patel",
          permissions: "rw-r--r--",
        },
        {
          name: "eslint.config.js",
          kind: "file",
          size: 980,
          modified: "2026-01-18T17:01:00Z",
          lastEditedBy: "Samir Patel",
          permissions: "rw-r--r--",
        },
      ],
    },
  ],
};
