name: Bug report
description: Create a bug report for LyteNyte Grid.
labels: ["pending", "bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for contributing by creating an issue! Please provide a searchable summary of the issue in the title above.
  - type: input
    attributes:
      label: Search keywords
      description: |
        Your issue may have already been reported! First search for duplicates among the [existing issues](https://github.com/1771-Technologies/lytenyte/issues).
        If your issue isn't a duplicate, great! Please list the keywords you used so people in the future can find this one more easily:
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: dropdown
    attributes:
      label: Affected products
      description: Which products are affected by this issue? If you're not sure, leave this blank.
      multiple: true
      options:
        - LyteNyte Grid Community
        - LyteNyte Grid Enterprise
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        **⚠️ Issues that we can't reproduce can't be fixed.**

        Please provide a link to a live example and an unambiguous set of steps to reproduce this bug. 
        See our [documentation](https://1771technologies/docs/support) on how to build a reproduction case.
      value: |
        Steps:
        1. Open this link to live example: (required)
        2.
        3.
  - type: textarea
    attributes:
      label: Current behavior
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Context
      description: What are you trying to accomplish? Providing context helps us come up with a solution that is more useful in the real world.
  - type: textarea
    attributes:
      label: Your environment
      description: Please provide your browser version and current OS.
      value: |
        ```
          Don't forget to mention which browser you used.
        ```
  - type: input
    id: contact
    attributes:
      label: Customer ID (optional)
      description: Enterprise customers can receive priority support. Providing your Customer ID gives your problem more attention.
      placeholder: "e.g. JANE-1221"
