name: " 🐛 Priority Bug Report"
description: Report a bug that should be looked at with priority
labels: ["pending", "bug", "priority"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        This issue tracker is for reporting reproducible bugs or regression's found in [LyteNyte Grid](https://github.com/1771-Technologies/lytenyte).
        If you have a question about how to achieve something and are struggling, please raise a 'General Questions' issue.

        The more information you fill in, the better we can help you.

  - type: input
    attributes:
      label: Search Keywords
      description: |
        Your issue may have already been reported! First search for duplicates among the [existing issues](https://github.com/1771-Technologies/lytenyte/issues).
        If your issue isn't a duplicate, great! Please list the keywords you used so people in the future can find this one more easily.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true

  - type: dropdown
    id: plan
    attributes:
      label: License Plan
      description: Which license plan are you on? (Priority bug reports may only be raised by license holders)
      multiple: false
      options:
        - PRO
        - Organization
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Your minimal, reproducible example
      description: |
        Please add a link to a minimal reproduction.
        Note: 
          - Your bug may get fixed much faster if we can run your code and it doesn't have dependencies other than React.
          - To create a shareable code example for web, you can use Stackblitz (https://stackblitz.com).
          - Please make sure the example is complete and runnable - e.g. avoid localhost URLs.
          - To stub out real api requests - Promise.resolve and Promise.reject are good options for easy reproductions
          - Feel free to fork any of the official examples to reproduce your issue (e.g. [the getting started stackblitz](https://stackblitz.com/fork/github/1771technologies/lytenyte/tree/main/examples/introduction/getting-started-final-demo))
          - ⚠️ Please do not expose any confidential information in your reproductions

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        **⚠️ Issues that we can't reproduce can't be fixed.**
      value: |
        Steps:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what should happen.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: |
        Following the repro steps above, how easily are you able to reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once

  - type: textarea
    attributes:
      label: Your environment
      description: Please provide your browser version and current OS.
      value: |
        ```
          Don't forget to mention which browser you used.
        ```
  - type: input
    id: contact
    attributes:
      label: Customer ID
      description: Please provide your customer ID.
      placeholder: "e.g. JANE-1221"
    validations:
      required: true
