name: "Priority Support: SLA ⏰"
description: I'm a LyteNyte Grid user and we have Priority Support through our license agreement.
title: "[question] "
labels: ["status: waiting for maintainer", "support: commercial", "support: unknown"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above.
  - type: input
    attributes:
      label: Search keywords
      description: |
        Your issue may have already been reported! First search for duplicates among the [existing issues](https://github.com/1771-Technologies/lytenyte/issues).
        If your issue isn't a duplicate, great! Please list the keywords you used so people in the future can find this one more easily:
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Please provide a link to a live example and an unambiguous set of steps to reproduce this bug. 
        See our [documentation](https://1771technologies/docs/support) on how to build a reproduction case.
      value: |
        Steps:
        1. Open this link to live example: (required)
        2.
        3.
  - type: textarea
    attributes:
      label: Your environment
      description: Please provide your browser version and current OS.
      value: |
        ```
          Don't forget to mention which browser you used.
        ```
  - type: input
    id: contact
    validation:
      require: true
    attributes:
      label: Customer ID (required)
      description: Enterprise customers can receive priority support. Providing your Customer ID gives your problem more attention.
      placeholder: "e.g. CUS-JANE-1221"
