name: "🏎️ Super Priority Bug Report"
description: Report a bug that should be addressed with super priority
labels: ["pending", "bug", "super-priority"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue.

        This tracker is specifically for reporting reproducible bugs or regressions in [LyteNyte Grid](https://github.com/1771-Technologies/lytenyte).
        For usage questions, please create a 'General Questions' issue instead.

        The more details you provide, the faster we can address your issue.

  - type: input
    attributes:
      label: Search Keywords
      description: |
        Please check if your issue has already been reported in our [existing issues](https://github.com/1771-Technologies/lytenyte/issues).
        If not, list keywords that others might use to find this issue in the future.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested with the latest version
          required: true

  - type: checkboxes
    attributes:
      label: Organization License Holder
      description: Super priority bug reports are only available to organization license holders.
      options:
        - label: I am an organization license holder
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the issue you're experiencing.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Minimal Reproduction Example
      description: |
        Please provide a link to a minimal reproduction of the issue.

        Tips:
        - Issues with reproducible examples are resolved much faster
        - Use Stackblitz (https://stackblitz.com) for shareable web examples
        - Ensure the example is complete and runnable without local dependencies
        - You can fork our official examples (e.g., [getting started stackblitz](https://stackblitz.com/fork/github/1771technologies/lytenyte/tree/main/examples/introduction/getting-started-final-demo))
        - ⚠️ Do not include any confidential information

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: |
        **⚠️ Issues we cannot reproduce cannot be fixed.**
      value: |
        Steps:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Issue Frequency
      description: |
        How consistently can you reproduce this issue?
      options:
        - Every time
        - Often
        - Sometimes
        - Rarely
        - Only once
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Details
      description: Please provide your browser version and operating system.
      value: |
        Browser: 
        Operating System: 
        LyteNyte Version:
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Customer ID
      description: Please provide your organization customer ID for super priority support.
      placeholder: "e.g. JANE-1221"
    validations:
      required: true
