name: "💡 Feature Request"
description: Request a new feature to be added to LyteNyte Grid
labels: ["pending", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a feature.

        This tracker is specifically for requesting new features for [LyteNyte Grid](https://github.com/1771-Technologies/lytenyte).
        For usage questions, please create a 'General Questions' issue instead.

        The more details you provide, the better we can understand your needs.

  - type: input
    attributes:
      label: Search Keywords
      description: |
        Please check if your feature has already been requested in our [existing feature requests](https://github.com/1771-Technologies/lytenyte/issues).
        If not, list keywords that others might use to find this feature request in the future.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested with the latest version
          required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you're requesting.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: Describe how you envision LyteNyte Grid implementing this feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Approaches
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any additional context, screenshots, or examples relevant to this feature request.
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Customer ID
      description: Please provide your customer ID (feature requests are for license holders).
      placeholder: "e.g. JANE-1221"
    validations:
      required: true
