name: "💡 Feature Request"
description:
labels: ["pending", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing by requesting a feature!

  - type: input
    attributes:
      label: Search Keywords
      description: |
        Your feature may have already been requested! First search for duplicates among 
        the [existing feature requests](https://github.com/1771-Technologies/lytenyte/issues).
        If your feature request isn't a duplicate, great! Please list the keywords you used so people in the future can find this one more easily.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true

  - type: dropdown
    id: plan
    attributes:
      label: License Plan
      description: Which license plan are you on? (If you do not have a license plan please select Core)
      multiple: false
      options:
        - Core (free)
        - PRO
        - Organization
  - type: dropdown
    attributes:
      label: LyteNyte Edition
      description: What edition of LyteNyte Grid are you using, Core or PRO?
      multiple: false
      options:
        - Core
        - PRO

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Provide a clear and concise description of the feature
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe how LyteNyte Grid should implement your requested feature
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative solutions
      description: Describe any alternatives you may have considered

  - type: textarea
    attributes:
      label: Additional context
      description: Please provide any additional context that may be relevant to the feature you
        have requested

  - type: input
    id: contact
    attributes:
      label: Customer ID
      description: License holders may raise feature requests
      placeholder: "e.g. JANE-1221"
    validations:
      required: true
