name: "📜 Documentation Feedback"
description: Submit suggestions for improving LyteNyte Grid documentation.
labels: ["documentation feedback", "status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help improve [LyteNyte Grid's](https://github.com/1771-Technologies/lytenyte) documentation. 
        Please provide a clear, informative, and searchable summary title above.

        For bug reports, regressions, feature requests, or general questions about 
        using LyteNyte Grid, please use the appropriate issue template.
  - type: input
    attributes:
      label: Search Keywords
      description: |
        Before submitting your feedback, please review our [existing feedback](https://github.com/1771-Technologies/lytenyte/issues)
        to ensure there are no duplicates. If no match is found, list the keywords you used to improve future discoverability.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Latest Version
      description: We integrate bug fixes, performance enhancements, and other improvements in each new release.
      options:
        - label: I have tested the latest version
          required: true

  - type: input
    id: page-url
    attributes:
      label: Related Page
      description: Please paste the URL of the documentation page that your feedback refers to.
      placeholder: https://1771technologies/docs/
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Feedback Type
      description: Select the type of documentation issue.
      options:
        - Explanation is unclear
        - Explanation lacks detail
        - Information is outdated
        - Information is missing
        - Demo is broken
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Your Feedback
      description: Please describe what didn’t work and suggest how we can improve the documentation. Be as detailed and specific as possible.
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Customer ID (Optional)
      description: PRO license holders are entitled to priority review by including their customer ID when submitting documentation feedback.
      placeholder: "e.g. JANE-1221"
