name: "📝 Documentation Feedback"
description: Provide feedback to improve LyteNyte Grid documentation
labels: ["pending", "docs-feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to provide documentation feedback.

        This tracker is specifically for suggesting improvements to the 
        [LyteNyte Grid](https://github.com/1771-Technologies/lytenyte) documentation. For bug reports or 
        feature requests, please use the appropriate issue templates.

        The more details you provide, the better we can improve our documentation.

  - type: input
    attributes:
      label: Search Keywords
      description: |
        Please check if your feedback has already been suggested in our [existing feedback](https://github.com/1771-Technologies/lytenyte/issues).
        If not, list keywords that others might use to find this feedback in the future.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested with the latest version
          required: true

  - type: input
    id: page-url
    attributes:
      label: Related Page
      description: Which page of the documentation does this feedback apply to?
      placeholder: https://1771technologies/docs/
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Feedback Type
      description: What type of documentation issue are you reporting?
      options:
        - Unclear explanations
        - Missing information
        - Broken demo
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Your Feedback
      description: Provide a clear and concise description of the suggested improvements.
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Customer ID (optional)
      description: License holders receive priority support. Your Customer ID helps us provide faster assistance.
      placeholder: "e.g. JANE-1221"
