// @ts-nocheck -- skip type checking
import * as guides_6 from "../src/guides/(001+)/(001+-Getting Started)/getting-started/getting-started-pro.mdx?collection=guides&hash=1751314030328"
import * as guides_5 from "../src/guides/(001+)/(001+-Getting Started)/getting-started/getting-started-core.mdx?collection=guides&hash=1751314030328"
import * as guides_4 from "../src/guides/(001+)/index.mdx?collection=guides&hash=1751314030328"
import * as guides_3 from "../src/guides/(002+-Production Ready)/license-activation.mdx?collection=guides&hash=1751314030328"
import * as guides_2 from "../src/guides/(002+-Production Ready)/installation.mdx?collection=guides&hash=1751314030328"
import * as guides_1 from "../src/guides/(002+-Production Ready)/grid-versioning.mdx?collection=guides&hash=1751314030328"
import * as guides_0 from "../src/guides/(002+-Production Ready)/bundling-and-tree-shaking.mdx?collection=guides&hash=1751314030328"
import * as reference_0 from "../src/reference/(001)/index.mdx?collection=reference&hash=1751314030328"
import * as changelog_0 from "../src/changelog/(001)/index.mdx?collection=changelog&hash=1751314030328"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const changelog = _runtime.docs<typeof _source.changelog>([{ info: {"path":"(001)/index.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/changelog/(001)/index.mdx"}, data: changelog_0 }], [])
export const guides = _runtime.docs<typeof _source.guides>([{ info: {"path":"(002+-Production Ready)/bundling-and-tree-shaking.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/guides/(002+-Production Ready)/bundling-and-tree-shaking.mdx"}, data: guides_0 }, { info: {"path":"(002+-Production Ready)/grid-versioning.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/guides/(002+-Production Ready)/grid-versioning.mdx"}, data: guides_1 }, { info: {"path":"(002+-Production Ready)/installation.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/guides/(002+-Production Ready)/installation.mdx"}, data: guides_2 }, { info: {"path":"(002+-Production Ready)/license-activation.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/guides/(002+-Production Ready)/license-activation.mdx"}, data: guides_3 }, { info: {"path":"(001+)/index.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/guides/(001+)/index.mdx"}, data: guides_4 }, { info: {"path":"(001+)/(001+-Getting Started)/getting-started/getting-started-core.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/guides/(001+)/(001+-Getting Started)/getting-started/getting-started-core.mdx"}, data: guides_5 }, { info: {"path":"(001+)/(001+-Getting Started)/getting-started/getting-started-pro.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/guides/(001+)/(001+-Getting Started)/getting-started/getting-started-pro.mdx"}, data: guides_6 }], [])
export const reference = _runtime.docs<typeof _source.reference>([{ info: {"path":"(001)/index.mdx","absolutePath":"/Users/leebeydoun/Workspace/lytenyte/v1-migration-folder/sites/lytenyte-docs/src/reference/(001)/index.mdx"}, data: reference_0 }], [])