import type { ColumnEnterpriseReact } from "@1771technologies/grid-types";

export const columns: ColumnEnterpriseReact<any>[] = [
  { id: "age", type: "number" },
  { id: "job" },
  { id: "balance", type: "number" },
  { id: "education" },
  { id: "marital" },
  { id: "default" },
  { id: "housing" },
  { id: "loan" },
  { id: "contact" },
  { id: "day" },
  { id: "month" },
  { id: "duration" },
  { id: "campaign" },
  { id: "pdays" },
  { id: "previous" },
  { id: "poutcome" },
  { id: "y" },
];
export const bankColumns: ColumnEnterpriseReact<any>[] = [
  { id: "age", groupPath: ["Information"] },
  { id: "job", cellEditPredicate: true, groupPath: ["Information"], rowGroupable: true },
  { id: "balance", pin: "start", measureFn: "sum" },
  { id: "education", groupPath: ["Information"], rowGroupable: true },
  { id: "marital", groupPath: ["Information"] },
  { id: "default", columnPivotable: true },
  { id: "housing", columnPivotable: true, aggFn: "count", rowGroupable: true },
  { id: "loan", pin: "start", columnPivotable: true },
  { id: "contact", pin: "end", aggFn: "sum" },
  { id: "day", rowGroupable: true, aggFnDefault: "first", aggFnsAllowed: ["first", "last"] },
  { id: "month", measureFn: "count" },
  { id: "duration" },
  { id: "campaign" },
  { id: "pdays" },
  { id: "previous" },
  { id: "poutcome", measureFnsAllowed: ["sum", "count"], measureFnDefault: "count" },
  { id: "y", measureFnsAllowed: ["sum", "count"] },
];
