export const collapseChildData = [
  {
    athlete: "Fabio",
    country: "France",
    city: "Paris",
    year: "2016",
    gold: 10,
    silver: 10,
    bronze: 10,
  },
  {
    athlete: "Ricard",
    country: "France",
    city: "Paris",
    year: "2016",
    gold: 5,
    silver: 5,
    bronze: 5,
  },
  {
    athlete: "Rob",
    country: "France",
    city: "Paris",
    year: "2016",
    gold: 2,
    silver: 2,
    bronze: 2,
  },
  {
    athlete: "Sam",
    country: "England",
    city: "London",
    year: "2016",
    gold: 2,
    silver: 2,
    bronze: 2,
  },
  {
    athlete: "Truman",
    country: "Scotland",
    city: "Glasgow",
    year: "2016",
    gold: 2,
    silver: 2,
    bronze: 2,
  },
  {
    athlete: "Tom",
    country: "South Africa",
    city: "Cape Town",
    year: "2016",
    gold: 2,
    silver: 2,
    bronze: 2,
  },
  {
    athlete: "Alpha",
    country: "South Africa",
    city: "Johannesburg",
    year: "2016",
    gold: 2,
    silver: 2,
    bronze: 2,
  },
  {
    athlete: "Jack",
    country: "Germany",
    city: "Berlin",
    year: "2016",
    gold: 2,
    silver: 2,
    bronze: 2,
  },
  {
    athlete: "Roma",
    country: "Italy",
    city: "Rome",
    year: "2016",
    gold: 2,
    silver: 2,
    bronze: 2,
  },
];
