/* v8 ignore start */
export const columnPivots = [
  {
    id: "exchange",
    columnPivotable: true,
    columnPivotField: "exchange",
    aggFunc: "count",
  },
  {
    id: "symbol",
    columnPivotable: true,
    columnPivotField: "symbol",
    sortComparator: "string",
    cellEditPredicate: true,
  },
  {
    id: "currency",
    columnPivotField: "currency",
    columnPivotable: true,
  },
  {
    id: "sector",
    columnPivotField: "sector",
    columnPivotable: true,
    filterQuickSearchable: true,
  },
  {
    id: "industry",
    rowGroupable: true,
    measureFunc: () => 23,
  },
  {
    id: "price",
    aggFunc: "sum",
    measureFunc: "sum",
    sortComparator: "number",
  },
  { id: "volume", aggFunc: "avg", measureFunc: "sum" },
];

export const pivotData = [
  {
    exchange: "NASDAQ",
    symbol: "ESGR",
    currency: "PHP",
    sector: "Finance",
    industry: "Property-Casualty Insurers",
    price: 74.89,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "LSXMA",
    currency: "IDR",
    sector: "Consumer Services",
    industry: null,
    price: 183.03,
    volume: 154810,
  },
  {
    exchange: "NYSE",
    symbol: "XPO",
    currency: "SEK",
    sector: "Consumer Services",
    industry: "Transportation Services",
    price: 904.86,
    volume: null,
  },
  {
    exchange: "NYSE",
    symbol: "LGF.B",
    currency: "CAD",
    sector: "n/a",
    industry: null,
    price: 988.9,
    volume: 33213,
  },
  {
    exchange: "NYSE",
    symbol: "TRMR",
    currency: "KES",
    sector: "Technology",
    industry: "Advertising",
    price: 776.96,
    volume: 121903,
  },
  {
    exchange: "NYSE",
    symbol: "TGP",
    currency: "IDR",
    sector: "Consumer Services",
    industry: null,
    price: 1049.96,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "ISBC",
    currency: "MGA",
    sector: "Finance",
    industry: null,
    price: 1152.36,
    volume: 82793,
  },
  {
    exchange: "NASDAQ",
    symbol: "TCBIW",
    currency: "RUB",
    sector: "Finance",
    industry: "Major Banks",
    price: 1440.52,
    volume: 26228,
  },
  {
    exchange: "NYSE",
    symbol: "ASA",
    currency: "KMF",
    sector: "n/a",
    industry: "n/a",
    price: 1991.72,
    volume: 174020,
  },
  {
    exchange: "NYSE",
    symbol: "TEN",
    currency: "RUB",
    sector: "Capital Goods",
    industry: "Auto Parts:O.E.M.",
    price: 1374.92,
    volume: 115657,
  },
  {
    exchange: "NASDAQ",
    symbol: "VEACW",
    currency: "JPY",
    sector: "Finance",
    industry: null,
    price: 457.2,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "SPLS",
    currency: "EUR",
    sector: "Consumer Services",
    industry: "Other Specialty Stores",
    price: 25.77,
    volume: 52383,
  },
  {
    exchange: "NYSE",
    symbol: "BGCA",
    currency: "CVE",
    sector: "Finance",
    industry: "Investment Bankers/Brokers/Service",
    price: 1313.73,
    volume: 148776,
  },
  {
    exchange: "NASDAQ",
    symbol: "CLIR",
    currency: "CZK",
    sector: "Capital Goods",
    industry: null,
    price: 648.08,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "EMCG",
    currency: "CNY",
    sector: "n/a",
    industry: "n/a",
    price: 674.99,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "CELG",
    currency: "BRL",
    sector: "Health Care",
    industry: "Major Pharmaceuticals",
    price: 178.18,
    volume: 92683,
  },
  {
    exchange: "NASDAQ",
    symbol: "EXTR",
    currency: "COP",
    sector: "Technology",
    industry: "Computer Communications Equipment",
    price: 63.48,
    volume: 56853,
  },
  {
    exchange: "NYSE",
    symbol: "UZA",
    currency: "CNY",
    sector: "Public Utilities",
    industry: "Telecommunications Equipment",
    price: 1915.53,
    volume: 122514,
  },
  {
    exchange: "NASDAQ",
    symbol: "JASNW",
    currency: "PHP",
    sector: "Consumer Durables",
    industry: "Miscellaneous manufacturing industries",
    price: 1231.11,
    volume: 188898,
  },
  {
    exchange: "NYSE",
    symbol: "TCO^J",
    currency: "EUR",
    sector: "n/a",
    industry: "n/a",
    price: 1567.51,
    volume: 50151,
  },
  {
    exchange: "NASDAQ",
    symbol: "RTK",
    currency: "SEK",
    sector: "Basic Industries",
    industry: "Agricultural Chemicals",
    price: 167.66,
    volume: 77386,
  },
  {
    exchange: "NYSE",
    symbol: "PVG",
    currency: "SEK",
    sector: "Basic Industries",
    industry: "Precious Metals",
    price: 561.45,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "FTFT",
    currency: "IDR",
    sector: "Consumer Non-Durables",
    industry: "Packaged Foods",
    price: 566.51,
    volume: 161883,
  },
  {
    exchange: "NYSE",
    symbol: "ORI",
    currency: "ARS",
    sector: "Finance",
    industry: "Property-Casualty Insurers",
    price: 871.79,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "SEDG",
    currency: "CNY",
    sector: "Technology",
    industry: null,
    price: 366.58,
    volume: 150676,
  },
  {
    exchange: "NYSE",
    symbol: "HTA",
    currency: "BDT",
    sector: "Consumer Services",
    industry: "Real Estate Investment Trusts",
    price: 889.76,
    volume: 123181,
  },
  {
    exchange: "NASDAQ",
    symbol: "DRNA",
    currency: "AZN",
    sector: "Health Care",
    industry: "Major Pharmaceuticals",
    price: 671.66,
    volume: null,
  },
  {
    exchange: "NYSE",
    symbol: "GOLF",
    currency: "IDR",
    sector: "Consumer Non-Durables",
    industry: "Recreational Products/Toys",
    price: 1414.7,
    volume: 74128,
  },
  {
    exchange: "NASDAQ",
    symbol: "MLAB",
    currency: "SEK",
    sector: "Capital Goods",
    industry: "Industrial Machinery/Components",
    price: 1767.57,
    volume: 12577,
  },
  {
    exchange: "NYSE",
    symbol: "MED",
    currency: "BRL",
    sector: "Consumer Non-Durables",
    industry: "Packaged Foods",
    price: 1153.35,
    volume: 39147,
  },
  {
    exchange: "NYSE",
    symbol: "VOC",
    currency: "EUR",
    sector: "Energy",
    industry: "Oil & Gas Production",
    price: 1611.29,
    volume: 166693,
  },
  {
    exchange: "NASDAQ",
    symbol: "AMBC",
    currency: "JPY",
    sector: "Finance",
    industry: "Property-Casualty Insurers",
    price: 1551.4,
    volume: 187635,
  },
  {
    exchange: "NASDAQ",
    symbol: "MGRC",
    currency: "SEK",
    sector: "Technology",
    industry: "Diversified Commercial Services",
    price: 1960.84,
    volume: 109779,
  },
  {
    exchange: "NASDAQ",
    symbol: "MMLP",
    currency: "BGN",
    sector: "Energy",
    industry: "Oil Refining/Marketing",
    price: 26.53,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "ETSY",
    currency: "BAM",
    sector: "Miscellaneous",
    industry: "Business Services",
    price: 1500.54,
    volume: 124211,
  },
  {
    exchange: "NASDAQ",
    symbol: "SYBT",
    currency: "SEK",
    sector: "Finance",
    industry: "Major Banks",
    price: 564.41,
    volume: 86488,
  },
  {
    exchange: "NASDAQ",
    symbol: "INTG",
    currency: "CNY",
    sector: "Consumer Services",
    industry: "Building operators",
    price: 1210.99,
    volume: 155309,
  },
  {
    exchange: "NASDAQ",
    symbol: "HRTX",
    currency: "IDR",
    sector: "Health Care",
    industry: null,
    price: 651.89,
    volume: 169830,
  },
  {
    exchange: "NYSE",
    symbol: "TCRX",
    currency: "PEN",
    sector: "n/a",
    industry: "n/a",
    price: 1919.36,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "NSSC",
    currency: "TTD",
    sector: "Consumer Durables",
    industry: "Telecommunications Equipment",
    price: 919.55,
    volume: 12328,
  },
  {
    exchange: "NYSE",
    symbol: "TMK",
    currency: "EUR",
    sector: "Finance",
    industry: "Life Insurance",
    price: 1833.61,
    volume: null,
  },
  {
    exchange: "NYSE",
    symbol: "IDA",
    currency: "MGA",
    sector: "Public Utilities",
    industry: "Electric Utilities: Central",
    price: 1950.12,
    volume: 93682,
  },
  {
    exchange: "NASDAQ",
    symbol: "LMNX",
    currency: "PLN",
    sector: "Health Care",
    industry: "Medical/Dental Instruments",
    price: 1307.15,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "CASM",
    currency: "THB",
    sector: "Health Care",
    industry: "Medical/Dental Instruments",
    price: 801.59,
    volume: null,
  },
  {
    exchange: "NYSE",
    symbol: "KFY",
    currency: "PHP",
    sector: "Technology",
    industry: null,
    price: 498.27,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "INTG",
    currency: "EUR",
    sector: "Consumer Services",
    industry: "Building operators",
    price: 1737.83,
    volume: 82881,
  },
  {
    exchange: "NASDAQ",
    symbol: "KE",
    currency: "MYR",
    sector: "Technology",
    industry: "Electrical Products",
    price: 775.13,
    volume: 157975,
  },
  {
    exchange: "NYSE",
    symbol: "CIG.C",
    currency: "IDR",
    sector: "n/a",
    industry: "n/a",
    price: 415.96,
    volume: 27262,
  },
  {
    exchange: "NASDAQ",
    symbol: "JMU",
    currency: "PLN",
    sector: "Technology",
    industry: null,
    price: 1827.2,
    volume: null,
  },
  {
    exchange: "NASDAQ",
    symbol: "MBTF",
    currency: "EUR",
    sector: "Finance",
    industry: "Major Banks",
    price: 332.43,
    volume: null,
  },
];
