export const figmaData = [
  { id: "node_0001", groupPath: ["Home", "Header"], label: "Logo" },
  { id: "node_0002", groupPath: ["Home", "Header"], label: "NavItem_Home" },
  { id: "node_0003", groupPath: ["Home", "Header"], label: "NavItem_About" },
  { id: "node_0004", groupPath: ["Home", "Header"], label: "NavItem_Contact" },
  { id: "node_0005", groupPath: ["Home", "Hero"], label: "Headline" },
  { id: "node_0006", groupPath: ["Home", "Hero"], label: "Subheading" },
  { id: "node_0007", groupPath: ["Home", "Hero"], label: "CTA_Button" },
  { id: "node_0008", groupPath: ["Home", "Hero", "Background"], label: "Gradient" },
  { id: "node_0009", groupPath: ["Home", "Hero", "Background"], label: "Overlay" },
  { id: "node_0010", groupPath: ["Home", "Features"], label: "FeatureCard_1" },

  { id: "node_0011", groupPath: ["Home", "Features"], label: "FeatureCard_2" },
  { id: "node_0012", groupPath: ["Home", "Features"], label: "FeatureCard_3" },
  { id: "node_0013", groupPath: ["Home", "Footer"], label: "FooterText" },
  { id: "node_0014", groupPath: ["Home", "Footer"], label: "FooterLink_Terms" },
  { id: "node_0015", groupPath: ["Home", "Footer"], label: "FooterLink_Privacy" },
  { id: "node_0016", groupPath: ["Dashboard", "Sidebar"], label: "UserAvatar" },
  { id: "node_0017", groupPath: ["Dashboard", "Sidebar"], label: "MenuItem_1" },
  { id: "node_0018", groupPath: ["Dashboard", "Sidebar"], label: "MenuItem_2" },
  { id: "node_0019", groupPath: ["Dashboard", "Sidebar"], label: "MenuItem_3" },
  { id: "node_0020", groupPath: ["Dashboard", "Main"], label: "StatsCard_1" },

  { id: "node_0021", groupPath: ["Dashboard", "Main"], label: "StatsCard_2" },
  { id: "node_0022", groupPath: ["Dashboard", "Main"], label: "StatsCard_3" },
  { id: "node_0023", groupPath: ["Dashboard", "Main"], label: "Chart" },
  {
    id: "node_0024",
    groupPath: ["Dashboard", "Main", "Chart", "Legend"],
    label: "LegendItem_1",
  },
  {
    id: "node_0025",
    groupPath: ["Dashboard", "Main", "Chart", "Legend"],
    label: "LegendItem_2",
  },
  {
    id: "node_0026",
    groupPath: ["Dashboard", "Main", "Chart", "Legend"],
    label: "LegendItem_3",
  },
  { id: "node_0027", groupPath: ["Settings", "Profile"], label: "ProfilePic" },
  { id: "node_0028", groupPath: ["Settings", "Profile"], label: "NameField" },
  { id: "node_0029", groupPath: ["Settings", "Profile"], label: "EmailField" },
  { id: "node_0030", groupPath: ["Settings", "Preferences"], label: "Toggle_DarkMode" },

  { id: "node_0031", groupPath: ["Settings", "Preferences"], label: "Toggle_Notifications" },
  { id: "node_0032", groupPath: ["Settings", "Preferences"], label: "Toggle_Sounds" },
  { id: "node_0033", groupPath: ["Login"], label: "Login_Form" },
  { id: "node_0034", groupPath: ["Login"], label: "Input_Username" },
  { id: "node_0035", groupPath: ["Login"], label: "Input_Password" },
  { id: "node_0036", groupPath: ["Login"], label: "Button_Login" },
  { id: "node_0037", groupPath: ["Login"], label: "Link_ForgotPassword" },
  { id: "node_0038", groupPath: ["Register"], label: "Input_Email" },
  { id: "node_0039", groupPath: ["Register"], label: "Input_ConfirmPassword" },
  { id: "node_0040", groupPath: ["Register"], label: "Button_SignUp" },

  { id: "node_0041", groupPath: ["Modal", "ConfirmDelete"], label: "Text_Warning" },
  { id: "node_0042", groupPath: ["Modal", "ConfirmDelete"], label: "Button_Yes" },
  { id: "node_0043", groupPath: ["Modal", "ConfirmDelete"], label: "Button_No" },
  { id: "node_0044", groupPath: ["Modal", "Success"], label: "Icon_Check" },
  { id: "node_0045", groupPath: ["Modal", "Success"], label: "Text_Success" },
  { id: "node_0046", groupPath: ["Admin", "Users"], label: "Table_Header" },
  { id: "node_0047", groupPath: ["Admin", "Users"], label: "Table_Row_1" },
  { id: "node_0048", groupPath: ["Admin", "Users"], label: "Table_Row_2" },
  { id: "node_0049", groupPath: ["Admin", "Users"], label: "Table_Row_3" },
  { id: "node_0050", groupPath: ["Admin", "Users"], label: "Pagination" },

  { id: "node_0051", groupPath: ["Admin", "Reports"], label: "ReportCard_1" },
  { id: "node_0052", groupPath: ["Admin", "Reports"], label: "ReportCard_2" },
  { id: "node_0053", groupPath: ["Admin", "Reports"], label: "ReportCard_3" },
  { id: "node_0054", groupPath: ["Admin", "Reports"], label: "Export_Button" },
  { id: "node_0055", groupPath: ["Admin", "Reports"], label: "Filter_Menu" },
  { id: "node_0056", groupPath: ["Chat", "Thread"], label: "Message_1" },
  { id: "node_0057", groupPath: ["Chat", "Thread"], label: "Message_2" },
  { id: "node_0058", groupPath: ["Chat", "Thread"], label: "Message_3" },
  { id: "node_0059", groupPath: ["Chat", "Input"], label: "TextBox" },
  { id: "node_0060", groupPath: ["Chat", "Input"], label: "SendButton" },

  { id: "node_0061", groupPath: ["Chat", "Input"], label: "AttachmentIcon" },
  { id: "node_0062", groupPath: ["Notifications"], label: "NotificationCard_1" },
  { id: "node_0063", groupPath: ["Notifications"], label: "NotificationCard_2" },
  { id: "node_0064", groupPath: ["Notifications"], label: "NotificationCard_3" },
  { id: "node_0065", groupPath: ["Notifications"], label: "MarkAllRead_Button" },
  { id: "node_0066", groupPath: ["Profile", "Header"], label: "Profile_Banner" },
  { id: "node_0067", groupPath: ["Profile", "Header"], label: "EditButton" },
  { id: "node_0068", groupPath: ["Profile", "Details"], label: "UserName" },
  { id: "node_0069", groupPath: ["Profile", "Details"], label: "UserBio" },
  { id: "node_0070", groupPath: ["Profile", "Details"], label: "UserLocation" },

  { id: "node_0071", groupPath: ["Search"], label: "SearchBar" },
  { id: "node_0072", groupPath: ["Search"], label: "Result_1" },
  { id: "node_0073", groupPath: ["Search"], label: "Result_2" },
  { id: "node_0074", groupPath: ["Search"], label: "Result_3" },
  { id: "node_0075", groupPath: ["Search"], label: "ClearButton" },
  { id: "node_0076", groupPath: ["Files", "FileList"], label: "File_1" },
  { id: "node_0077", groupPath: ["Files", "FileList"], label: "File_2" },
  { id: "node_0078", groupPath: ["Files", "FileList"], label: "File_3" },
  { id: "node_0079", groupPath: ["Files", "Sidebar"], label: "Folder_Recent" },
  { id: "node_0080", groupPath: ["Files", "Sidebar"], label: "Folder_Shared" },

  { id: "node_0081", groupPath: ["Files", "Sidebar"], label: "Folder_Trash" },
  { id: "node_0082", groupPath: ["Help", "FAQ"], label: "Question_1" },
  { id: "node_0083", groupPath: ["Help", "FAQ"], label: "Question_2" },
  { id: "node_0084", groupPath: ["Help", "FAQ"], label: "Question_3" },
  { id: "node_0085", groupPath: ["Help", "Support"], label: "SupportForm" },
  { id: "node_0086", groupPath: ["Help", "Support"], label: "SubmitTicketButton" },
  { id: "node_0087", groupPath: ["Help", "Support"], label: "ChatWithSupport" },
  { id: "node_0088", groupPath: ["Blog", "Post_1"], label: "Title" },
  { id: "node_0089", groupPath: ["Blog", "Post_1"], label: "Author" },
  { id: "node_0090", groupPath: ["Blog", "Post_1"], label: "Body" },

  { id: "node_0091", groupPath: ["Blog", "Post_1"], label: "CoverImage" },
  { id: "node_0092", groupPath: ["Blog", "Post_2"], label: "Title" },
  { id: "node_0093", groupPath: ["Blog", "Post_2"], label: "Author" },
  { id: "node_0094", groupPath: ["Blog", "Post_2"], label: "Body" },
  { id: "node_0095", groupPath: ["Blog", "Post_2"], label: "CoverImage" },
  { id: "node_0096", groupPath: ["Blog", "Post_3"], label: "Title" },
  { id: "node_0097", groupPath: ["Blog", "Post_3"], label: "Author" },
  { id: "node_0098", groupPath: ["Blog", "Post_3"], label: "Body" },
  { id: "node_0099", groupPath: ["Blog", "Post_3"], label: "CoverImage" },
  { id: "node_0100", groupPath: ["Blog", "Post_3"], label: "CommentsSection" },

  { id: "node_0101", groupPath: [], label: "GlobalStyleSheet" },
  { id: "node_0102", groupPath: [], label: "DesignTokens" },
  { id: "node_0103", groupPath: ["Onboarding"], label: "StepIndicator" },
  { id: "node_0104", groupPath: ["Onboarding"], label: "Step_1" },
  { id: "node_0105", groupPath: ["Onboarding"], label: "Step_2" },
  { id: "node_0106", groupPath: ["Onboarding"], label: "Step_3" },
  { id: "node_0107", groupPath: ["Reports", "Charts"], label: "PieChart" },
  { id: "node_0108", groupPath: ["Reports", "Charts"], label: "BarChart" },
  { id: "node_0109", groupPath: ["Reports", "Charts"], label: "LineChart" },
  { id: "node_0110", groupPath: ["Reports", "Filters"], label: "DateRangePicker" },

  { id: "node_0111", groupPath: ["Reports", "Filters"], label: "Dropdown_Status" },
  { id: "node_0112", groupPath: ["Calendar"], label: "MonthView" },
  { id: "node_0113", groupPath: ["Calendar"], label: "WeekView" },
  { id: "node_0114", groupPath: ["Calendar"], label: "DayView" },
  { id: "node_0115", groupPath: ["Calendar"], label: "EventCard_1" },
  { id: "node_0116", groupPath: ["Calendar"], label: "EventCard_2" },
  { id: "node_0117", groupPath: ["Billing"], label: "InvoiceTable" },
  { id: "node_0118", groupPath: ["Billing"], label: "PaymentHistory" },
  { id: "node_0119", groupPath: ["Billing"], label: "AddPaymentMethod_Button" },
  { id: "node_0120", groupPath: [], label: "LogoGridBackground" },

  { id: "node_0121", groupPath: ["ActivityFeed"], label: "ActivityItem_1" },
  { id: "node_0122", groupPath: ["ActivityFeed"], label: "ActivityItem_2" },
  { id: "node_0123", groupPath: ["ActivityFeed"], label: "ActivityItem_3" },
  { id: "node_0124", groupPath: ["Search", "Filters"], label: "SearchByDate" },
  { id: "node_0125", groupPath: ["Search", "Filters"], label: "SearchByType" },
  { id: "node_0126", groupPath: ["Search", "Filters"], label: "SortDropdown" },
  { id: "node_0127", groupPath: ["Search", "NoResults"], label: "SuggestionCard_1" },
  { id: "node_0128", groupPath: ["Search", "NoResults"], label: "SuggestionCard_2" },
  { id: "node_0129", groupPath: ["Help", "LiveChat"], label: "ChatWindow" },
  { id: "node_0130", groupPath: ["Help", "LiveChat"], label: "ChatHeader" },

  { id: "node_0131", groupPath: ["Help", "LiveChat"], label: "ChatInput" },
  { id: "node_0132", groupPath: ["Settings", "Security"], label: "TwoFactorToggle" },
  { id: "node_0133", groupPath: ["Settings", "Security"], label: "SessionList" },
  { id: "node_0134", groupPath: ["Settings", "Security"], label: "LoginAlerts" },
  { id: "node_0135", groupPath: [], label: "Standalone_Spinner" },
  { id: "node_0136", groupPath: [], label: "FloatingMenu" },
  { id: "node_0137", groupPath: ["Editor"], label: "Toolbar" },
  { id: "node_0138", groupPath: ["Editor"], label: "Canvas" },
  { id: "node_0139", groupPath: ["Editor"], label: "LayerList" },
  { id: "node_0140", groupPath: ["Editor"], label: "PropertiesPanel" },

  { id: "node_0141", groupPath: ["Editor", "PropertiesPanel"], label: "ColorPicker" },
  { id: "node_0142", groupPath: ["Editor", "PropertiesPanel"], label: "TextAlign" },
  { id: "node_0143", groupPath: ["Editor", "PropertiesPanel"], label: "PaddingControl" },
  { id: "node_0144", groupPath: ["Editor", "Toolbar"], label: "Tool_Select" },
  { id: "node_0145", groupPath: ["Editor", "Toolbar"], label: "Tool_Rectangle" },
  { id: "node_0146", groupPath: ["Editor", "Toolbar"], label: "Tool_Text" },
  { id: "node_0147", groupPath: ["Editor", "Canvas"], label: "Artboard_1" },
  { id: "node_0148", groupPath: ["Editor", "Canvas"], label: "Artboard_2" },
  { id: "node_0149", groupPath: ["Editor", "Canvas", "Artboard_1"], label: "Rectangle_1" },
  { id: "node_0150", groupPath: ["Editor", "Canvas", "Artboard_1"], label: "Text_1" },

  { id: "node_0151", groupPath: ["Editor", "Canvas", "Artboard_2"], label: "Rectangle_2" },
  { id: "node_0152", groupPath: ["Editor", "Canvas", "Artboard_2"], label: "Text_2" },
  { id: "node_0153", groupPath: ["Media", "Gallery"], label: "Image_1" },
  { id: "node_0154", groupPath: ["Media", "Gallery"], label: "Image_2" },
  { id: "node_0155", groupPath: ["Media", "Gallery"], label: "Video_1" },
  { id: "node_0156", groupPath: ["Media", "Upload"], label: "DropZone" },
  { id: "node_0157", groupPath: ["Media", "Upload"], label: "UploadButton" },
  { id: "node_0158", groupPath: ["Media", "Upload"], label: "ProgressBar" },
  { id: "node_0159", groupPath: ["Media", "Upload"], label: "UploadSuccess" },
  { id: "node_0160", groupPath: [], label: "ThemePreview" },

  { id: "node_0161", groupPath: ["Dashboard", "QuickActions"], label: "Action_1" },
  { id: "node_0162", groupPath: ["Dashboard", "QuickActions"], label: "Action_2" },
  { id: "node_0163", groupPath: ["Dashboard", "QuickActions"], label: "Action_3" },
  { id: "node_0164", groupPath: ["Notifications", "Dropdown"], label: "Toggle" },
  { id: "node_0165", groupPath: ["Notifications", "Dropdown"], label: "Notification_1" },
  { id: "node_0166", groupPath: ["Notifications", "Dropdown"], label: "Notification_2" },
  { id: "node_0167", groupPath: [], label: "HoverOverlay" },
  { id: "node_0168", groupPath: [], label: "ScreenMask" },
  { id: "node_0169", groupPath: ["LandingPage"], label: "HeroImage" },
  { id: "node_0170", groupPath: ["LandingPage"], label: "PrimaryCTA" },

  {
    id: "node_0171",
    groupPath: ["LandingPage", "Testimonials"],
    label: "TestimonialCard_1",
  },
  {
    id: "node_0172",
    groupPath: ["LandingPage", "Testimonials"],
    label: "TestimonialCard_2",
  },
  {
    id: "node_0173",
    groupPath: ["LandingPage", "Testimonials"],
    label: "TestimonialCard_3",
  },
  { id: "node_0174", groupPath: ["LandingPage", "Pricing"], label: "PricingTable" },
  { id: "node_0175", groupPath: ["LandingPage", "Pricing"], label: "PlanCard_1" },
  { id: "node_0176", groupPath: ["LandingPage", "Pricing"], label: "PlanCard_2" },
  { id: "node_0177", groupPath: ["LandingPage", "Pricing"], label: "PlanCard_3" },
  { id: "node_0178", groupPath: [], label: "AppIconSet" },
  { id: "node_0179", groupPath: [], label: "TypographySpec" },
  { id: "node_0180", groupPath: ["Forms", "Survey"], label: "Question_1" },

  { id: "node_0181", groupPath: ["Forms", "Survey"], label: "Question_2" },
  { id: "node_0182", groupPath: ["Forms", "Survey"], label: "SubmitSurveyButton" },
  { id: "node_0183", groupPath: ["Forms", "Contact"], label: "NameField" },
  { id: "node_0184", groupPath: ["Forms", "Contact"], label: "MessageField" },
  { id: "node_0185", groupPath: ["Forms", "Contact"], label: "SendButton" },
  { id: "node_0186", groupPath: ["Forms", "Contact"], label: "ResetButton" },
  { id: "node_0187", groupPath: [], label: "ColorPalette" },
  { id: "node_0188", groupPath: [], label: "UI_Kit_Badge" },
  { id: "node_0189", groupPath: [], label: "UI_Kit_Card" },
  { id: "node_0190", groupPath: [], label: "UI_Kit_Alert" },

  { id: "node_0191", groupPath: [], label: "Detached_ArrowIcon" },
  { id: "node_0192", groupPath: ["Docs", "Sidebar"], label: "DocLink_1" },
  { id: "node_0193", groupPath: ["Docs", "Sidebar"], label: "DocLink_2" },
  { id: "node_0194", groupPath: ["Docs", "Sidebar"], label: "DocLink_3" },
  { id: "node_0195", groupPath: ["Docs", "Reader"], label: "Title" },
  { id: "node_0196", groupPath: ["Docs", "Reader"], label: "BodyText" },
  { id: "node_0197", groupPath: ["Docs", "Reader"], label: "ImageAttachment" },
  { id: "node_0198", groupPath: [], label: "BrandingLogo" },
  { id: "node_0199", groupPath: [], label: "PageGuideTip" },
  { id: "node_0200", groupPath: [], label: "KeyboardShortcutHint" },
];
