export const data = {
  root: {
    name: "root",
    kind: "folder",
    size: null,
    modified: "2026-01-22T09:00:00Z",
    "package.json": {
      name: "package.json",
      kind: "file",
      size: 1840,
      modified: "2026-01-21T18:12:00Z",
      lastEditedBy: "Joseph Allen",
      permissions: "rw-r--r--",
    },
    "package-lock.json": {
      name: "package-lock.json",
      kind: "file",
      size: 92000,
      modified: "2026-01-21T18:12:30Z",
      lastEditedBy: "Joseph Allen",
      permissions: "rw-r--r--",
    },
    "README.md": {
      name: "README.md",
      kind: "file",
      size: 1240,
      modified: "2026-01-20T10:05:00Z",
      lastEditedBy: "Betty Hall",
      permissions: "rw-r--r--",
    },

    public: {
      name: "public",
      kind: "folder",
      size: null,
      modified: "2026-01-18T12:00:00Z",
      "index.html": {
        name: "index.html",
        kind: "file",
        size: 3420,
        modified: "2026-01-18T12:01:00Z",
        lastEditedBy: "Charles Clark",
        permissions: "rw-r--r--",
      },
      "favicon.ico": {
        name: "favicon.ico",
        kind: "file",
        size: 5430,
        modified: "2026-01-18T12:01:30Z",
        lastEditedBy: "Charles Clark",
        permissions: "rw-r--r--",
      },
      "manifest.json": {
        name: "manifest.json",
        kind: "file",
        size: 820,
        modified: "2026-01-18T12:02:00Z",
        lastEditedBy: "Charles Clark",
        permissions: "rw-r--r--",
      },
      assets: {
        name: "assets",
        kind: "folder",
        size: null,
        modified: "2026-01-17T15:40:00Z",
        "logo.svg": {
          name: "logo.svg",
          kind: "file",
          size: 2048,
          modified: "2026-01-17T15:42:00Z",
          lastEditedBy: "Richard White",
          permissions: "rw-r--r--",
        },
        "hero.png": {
          name: "hero.png",
          kind: "file",
          size: 482000,
          modified: "2026-01-17T15:45:00Z",
          lastEditedBy: "Richard White",
          permissions: "rw-r--r--",
        },
      },
    },

    src: {
      name: "src",
      kind: "folder",
      size: null,
      modified: "2026-01-22T08:30:00Z",
      assets: {
        name: "assets",
        kind: "folder",
        size: null,
        modified: "2026-01-20T14:00:00Z",
        "global.css": {
          name: "global.css",
          kind: "file",
          size: 2140,
          modified: "2026-01-20T14:05:00Z",
          lastEditedBy: "Jennifer Taylor",
          permissions: "rw-r--r--",
        },
        "variables.css": {
          name: "variables.css",
          kind: "file",
          size: 980,
          modified: "2026-01-20T14:04:00Z",
          lastEditedBy: "Jennifer Taylor",
          permissions: "rw-r--r--",
        },

        components: {
          name: "components",
          kind: "folder",
          size: null,
          modified: "2026-01-21T09:30:00Z",
          Button: {
            name: "Button",
            kind: "folder",
            size: null,
            modified: "2026-01-21T09:31:00Z",
            "Button.jsx": {
              name: "Button.jsx",
              kind: "file",
              size: 1620,
              modified: "2026-01-21T09:35:00Z",
              lastEditedBy: "Sarah Wilson",
              permissions: "rw-r--r--",
            },
            "Button.module.css": {
              name: "Button.module.css",
              kind: "file",
              size: 740,
              modified: "2026-01-21T09:34:00Z",
              lastEditedBy: "Sarah Wilson",
              permissions: "rw-r--r--",
            },
            "Button.test.jsx": {
              name: "Button.test.jsx",
              kind: "file",
              size: 1280,
              modified: "2026-01-21T09:36:00Z",
              lastEditedBy: "Joseph Allen",
              permissions: "rw-r--r--",
            },
          },

          Modal: {
            name: "Modal",
            kind: "folder",
            size: null,
            modified: "2026-01-21T11:10:00Z",
            children: {
              "Modal.jsx": {
                name: "Modal.jsx",
                kind: "file",
                size: 1980,
                modified: "2026-01-21T11:15:00Z",
                lastEditedBy: "Nancy Lewis",
                permissions: "rw-r--r--",
              },
              "Modal.css": {
                name: "Modal.css",
                kind: "file",
                size: 860,
                modified: "2026-01-21T11:14:00Z",
                lastEditedBy: "Nancy Lewis",
                permissions: "rw-r--r--",
              },
            },
          },
        },
      },

      hooks: {
        name: "hooks",
        kind: "folder",
        size: null,
        modified: "2026-01-19T16:00:00Z",
        "useAuth.js": {
          name: "useAuth.js",
          kind: "file",
          size: 1320,
          modified: "2026-01-19T16:05:00Z",
          lastEditedBy: "Betty Hall",
          permissions: "rw-r--r--",
        },
        "useFetch.js": {
          name: "useFetch.js",
          kind: "file",
          size: 1740,
          modified: "2026-01-19T16:06:00Z",
          lastEditedBy: "Betty Hall",
          permissions: "rw-r--r--",
        },
      },

      context: {
        name: "context",
        kind: "folder",
        size: null,
        modified: "2026-01-20T10:40:00Z",
        "AuthContext.jsx": {
          name: "AuthContext.jsx",
          kind: "file",
          size: 1560,
          modified: "2026-01-20T10:42:00Z",
          lastEditedBy: "Jennifer Taylor",
          permissions: "rw-r--r--",
        },
      },

      services: {
        name: "services",
        kind: "folder",
        size: null,
        modified: "2026-01-20T11:30:00Z",
        "api.js": {
          name: "api.js",
          kind: "file",
          size: 980,
          modified: "2026-01-20T11:32:00Z",
          lastEditedBy: "Charles Clark",
          permissions: "rw-r--r--",
        },
        "authService.js": {
          name: "authService.js",
          kind: "file",
          size: 1420,
          modified: "2026-01-20T11:33:00Z",
          lastEditedBy: "Charles Clark",
          permissions: "rw-r--r--",
        },
      },

      utils: {
        name: "utils",
        kind: "folder",
        size: null,
        modified: "2026-01-19T15:10:00Z",
        "constants.js": {
          name: "constants.js",
          kind: "file",
          size: 540,
          modified: "2026-01-19T15:12:00Z",
          lastEditedBy: "Richard White",
          permissions: "rw-r--r--",
        },
        "formatDate.js": {
          name: "formatDate.js",
          kind: "file",
          size: 620,
          modified: "2026-01-19T15:11:00Z",
          lastEditedBy: "Richard White",
          permissions: "rw-r--r--",
        },
      },

      "routes.jsx": {
        name: "routes.jsx",
        kind: "file",
        size: 1240,
        modified: "2026-01-22T08:10:00Z",
        lastEditedBy: "Sarah Wilson",
        permissions: "rw-r--r--",
      },
      "App.jsx": {
        name: "App.jsx",
        kind: "file",
        size: 2140,
        modified: "2026-01-22T08:20:00Z",
        lastEditedBy: "Sarah Wilson",
        permissions: "rw-r--r--",
      },
      "main.jsx": {
        name: "main.jsx",
        kind: "file",
        size: 860,
        modified: "2026-01-22T08:25:00Z",
        lastEditedBy: "Sarah Wilson",
        permissions: "rw-r--r--",
      },
    },

    tests: {
      name: "tests",
      kind: "folder",
      size: null,
      modified: "2026-01-21T13:00:00Z",
      "setupTests.js": {
        name: "setupTests.js",
        kind: "file",
        size: 520,
        modified: "2026-01-21T13:01:00Z",
        lastEditedBy: "Joseph Allen",
        permissions: "rw-r--r--",
      },
      "App.test.jsx": {
        name: "App.test.jsx",
        kind: "file",
        size: 1620,
        modified: "2026-01-21T13:02:00Z",
        lastEditedBy: "Joseph Allen",
        permissions: "rw-r--r--",
      },
    },

    config: {
      name: "config",
      kind: "folder",
      size: null,
      modified: "2026-01-18T17:00:00Z",
      "vite.config.js": {
        name: "vite.config.js",
        kind: "file",
        size: 1120,
        modified: "2026-01-18T17:02:00Z",
        lastEditedBy: "Betty Hall",
        permissions: "rw-r--r--",
      },
      "eslint.config.js": {
        name: "eslint.config.js",
        kind: "file",
        size: 980,
        modified: "2026-01-18T17:01:00Z",
        lastEditedBy: "Betty Hall",
        permissions: "rw-r--r--",
      },
    },
  },
};
