import type { InterfaceType, UnionType } from "../+types.js";

export const ColumnGroupMeta: InterfaceType = {
  kind: "interface",
  name: "ColumnGroupMeta",
  export: true,
  tsDoc: `
  Provides metadata related to column groups in LyteNyte Grid.

  This metadata is auto-generated by the grid based on the configured column definitions.
  It is used internally to manage layout and grouping behavior, but is also exposed for
  advanced use cases where programmatic interaction with group structures is needed.

  @group Column Groups
  `,
  doc: { en: `` },
  properties: [
    {
      kind: "property",
      name: "colIdToGroupIds",
      value: "Map<string, string[]>",
      doc: { en: `` },
      optional: false,
      tsDoc: `
      A map linking each column id to its associated group id hierarchy.

      Only populated for columns that belong to at least one group. The group ids reflect the
      nesting structure and are ordered from outermost to innermost group.
      `,
    },
    {
      kind: "property",
      name: "validGroupIds",
      value: "Set<string>",
      doc: { en: `` },
      optional: false,
      tsDoc: `
      A set of all valid group ids found in the grid.

      Group ids are derived by joining nested group names using the configured group delimiter.
      Used for validation, lookup, and rendering logic.
      `,
    },
    {
      kind: "property",
      name: "groupIsCollapsible",
      value: "Map<string, boolean>",
      doc: { en: `` },
      optional: false,
      tsDoc: `
      Indicates whether a given column group is collapsible.

      For a group to be collapsible:
      - It must contain at least one column visible when the group is **collapsed**
      - It must also contain at least one column visible only when the group is **expanded**

      The map uses group ids as keys and a boolean as the value.
      `,
    },
  ],
};

export const ColumnGroupVisibility: UnionType = {
  kind: "union",
  name: "ColumnGroupVisibility",
  export: true,
  tsDoc: `
  Controls the visibility behavior of a column within a column group.
    - \`"always"\`: The column is always visible regardless of the group's state.
    - \`"close"\`: The column is visible only when the group is **collapsed**.
    - \`"open"\`: The column is visible only when the group is **expanded**.

  Used to build dynamic, collapsible column group layouts in LyteNyte Grid.

  @group Column Groups
  `,
  doc: { en: `` },
  types: ['"always"', '"close"', '"open"'],
};
