import type { ColumnProReact } from "@1771technologies/grid-types/pro-react";
import type { DataEntry } from "./high-frequency-data";

export const hfColumns: ColumnProReact<DataEntry>[] = [
  {
    id: "volume",
    headerName: "Volume",
    type: "complex",
    aggFnDefault: "group",
  },
  {
    id: "bid",
    headerName: "Bid",
    groupPath: ["Book"],
    type: "number",
    aggFnDefault: "avg",
    groupVisibility: "always-visible",
    width: 120,
    widthFlex: 1,
    aggFnsAllowed: ["first", "last", "count", "min", "max", "avg", "sum"],
  },
  {
    id: "ask",
    headerName: "Ask",
    groupPath: ["Book"],
    type: "number",
    aggFnDefault: "avg",
    groupVisibility: "always-visible",
    width: 120,
    widthFlex: 1,
    aggFnsAllowed: ["first", "last", "count", "min", "max", "avg", "sum"],
  },
  {
    id: "spread",
    headerName: "Spread",
    groupPath: ["Book"],
    type: "number",
    aggFnDefault: "avg",
    groupVisibility: "always-visible",
    width: 120,
    widthFlex: 1,
    aggFnsAllowed: ["first", "last", "count", "min", "max", "avg", "sum"],
  },

  {
    id: "volatility",
    headerName: "Volatility",
    groupPath: ["Metrics"],
    aggFnDefault: "avg",
    type: "number",
    groupVisibility: "always-visible",
    width: 120,
    widthFlex: 1,
    aggFnsAllowed: ["first", "last", "count", "min", "max", "avg", "sum"],
  },
  {
    id: "latency",
    headerName: "Latency",
    groupPath: ["Metrics"],
    aggFnDefault: "avg",
    type: "number",
    groupVisibility: "always-visible",
    width: 120,
    widthFlex: 1,
    aggFnsAllowed: ["first", "last", "count", "min", "max", "avg", "sum"],
  },
  {
    id: "pnl",
    headerName: "P&L",
    groupPath: ["Metrics"],
    aggFnDefault: "first",
    type: "number",
    groupVisibility: "always-visible",
    width: 120,
    widthFlex: 1,
    aggFnsAllowed: ["first", "last", "count", "min", "max", "avg", "sum"],
  },

  {
    id: "symbol",
    headerName: "Symbol",
    rowGroupable: true,
    hide: true,
    groupVisibility: "always-visible",
    type: "number",
    aggFnDefault: "first",
    aggFnsAllowed: ["first", "last", "count", "min", "max", "avg", "sum"],
  },

  {
    id: "time",
    headerName: "Time",
    width: 120,
    groupVisibility: "always-visible",
    aggFnDefault: "first",
    aggFnsAllowed: ["first", "last", "min", "max"],
  },
];
